# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
        mime_types:
            json: [ 'application/json; charset=UTF-8' ]
        formats:
            json: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
    zone:
        - { host: ^api\. }
    exception:
        map_exception_codes: true
        codes:
            'InvalidArgumentException': 422
            'Doctrine\ORM\EntityNotFoundException': 404
        messages:
            'InvalidArgumentException': true
            'Doctrine\ORM\EntityNotFoundException': true
