version: "3.9"
services:

    #PHP Service
    php:
        platform: linux/amd64
        build:
            context: .
            dockerfile: setup/fpm/Dockerfile
        container_name: cosmos-odyssey-php
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www:delegated
        networks:
            - cosmos_odyssey_backend
        environment:
            - TZ=Europe/Tallinn

    #MySQL Service
    db:
        platform: linux/amd64
        image: mysql:8.0.33
        container_name: cosmos-odyssey-mysql
        restart: always
        environment:
            MYSQL_DATABASE: cosmos_odyssey
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
            MYSQL_TCP_PORT: 2208
        ports:
            - "2208:2208"
        volumes:
            - mysql-data:/var/lib/mysql:rw
        networks:
            - cosmos_odyssey_backend

    #Nginx Service
    nginx:
        depends_on:
            - php
        image: nginx:stable-alpine
        container_name: cosmos-odyssey-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./setup/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "2626:2626"
        networks:
            - cosmos_odyssey_backend

#Docker Networks
networks:
    cosmos_odyssey_backend:
        driver: bridge
volumes:
    mysql-data: